yit_help:
    resource: "@TmcycyitHelpBundle/Controller/"
    type:     annotation
    prefix:   /

help_article_rest:
    type:     rest
    resource: Tmcycyit\HelpBundle\Controller\Rest\ArticleController

help_category_rest:
    type:     rest
    resource: Tmcycyit\HelpBundle\Controller\Rest\CategoryController