yit_help:
    resource: "@YitHelpBundle/Controller/"
    type:     annotation
    prefix:   /
    
help_article_rest:
    type:     rest
    resource: Yit\HelpBundle\Controller\Rest\ArticleController

help_category_rest:
    type:     rest
    resource: Yit\HelpBundle\Controller\Rest\CategoryController

